version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'  # Redirecciona el puerto 3000 del contenedor al puerto 3000 del host
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
